#
# Makefile for 2560 AVR chips
#
# * Copyright 2013-2015 by Bill Westfield, Marek Wodzinski.  Part of Optiboot.
# * This software is licensed under version 2 of the Gnu Public Licence.
# * See optiboot.c for details.

# Chip level targets
#
ifdef CURRENT_DEVOBOARD_VERSION
  CURRENT_DEVOBOARD_VERSION_MAJOR=$(shell echo $$(($(CURRENT_DEVOBOARD_VERSION) / 0x10)))
  CURRENT_DEVOBOARD_VERSION_MINOR=$(shell echo $$(($(CURRENT_DEVOBOARD_VERSION) % 0x10)))
  COMPATIBLE_DEVOBOARD_VERSION_MAJOR=$(shell echo $$(($(COMPATIBLE_DEVOBOARD_VERSION) / 0x10)))
  COMPATIBLE_DEVOBOARD_VERSION_MINOR=$(shell echo $$(($(COMPATIBLE_DEVOBOARD_VERSION) % 0x10)))
  DEVOBOARD_VERSION=devoboard-$(CURRENT_DEVOBOARD_VERSION_MAJOR).$(CURRENT_DEVOBOARD_VERSION_MINOR)
endif

OPTIBOOT_VERSION:=$(shell git describe --exact-match --dirty 2> /dev/null)
ifeq ($(OPTIBOOT_VERSION),)
  OPTIBOOT_VERSION=dev
endif


atmega2560: TARGET = atmega2560
atmega2560: MCU_TARGET = atmega2560
atmega2560: CFLAGS += $(COMMON_OPTIONS) -DBIGBOOT
atmega2560: AVR_FREQ ?= 16000000L
atmega2560: LDSECTIONS  = -Wl,--section-start=.text=0x3fc00 -Wl,--section-start=.version=0x3fffc
atmega2560: CFLAGS += $(UART_CMD) -DCURRENT_DEVOBOARD_VERSION=$(CURRENT_DEVOBOARD_VERSION) -DCOMPATIBLE_DEVOBOARD_VERSION=$(COMPATIBLE_DEVOBOARD_VERSION)
atmega2560: $(PROGRAM)-$(OPTIBOOT_VERSION)-$(DEVOBOARD_VERSION).hex
atmega2560: $(PROGRAM)-$(OPTIBOOT_VERSION)-$(DEVOBOARD_VERSION).lst


atmega2560_isp: atmega2560
atmega2560_isp: TARGET = atmega2560
atmega2560_isp: MCU_TARGET = atmega2560
# 1024 byte boot, JTAG disabled
atmega2560_isp: HFUSE ?= DE
# Full Swing xtal (16MHz) 16KCK/14CK+65ms
atmega2560_isp: LFUSE ?= F7
# 2.7V brownout
atmega2560_isp: EFUSE ?= FD
atmega2560_isp: isp

#
# Board-level targets
#

# Arduino/Geniuno MEGA 256 has a minimum boot size of 1024 bytes, so enable extra functions
#
mega2560: TARGET = $@
mega2560: CHIP = atmega2560
mega2560:
	$(MAKE) $(CHIP) AVR_FREQ=16000000L
	mv $(PROGRAM)_$(CHIP).hex $(PROGRAM)_$(TARGET).hex
	mv $(PROGRAM)_$(CHIP).lst $(PROGRAM)_$(TARGET).lst

mega2560_isp: mega256
mega2560_isp: TARGET = mega2560
mega2560_isp: MCU_TARGET = atmega2560
# 1024 byte boot, JTAG disabled
mega2560_isp: HFUSE ?= DE
# Full swing xtal (16MHz) 16KCK/14CK+65ms
mega2560_isp: LFUSE ?= F7
# 2.7V brownout
mega2560_isp: EFUSE ?= FD
mega2560_isp: isp

